/* =========================================================
   SZEFO.HU – KERESÉSI ADATOK
   Fájl helye: js/search_data.js
   Betöltés: search.js előtt.

   Megjegyzés:
   Az URL-ek a hu/kereses/index.html oldalhoz képest relatívak.
   A lista bővíthető új oldalakkal, kulcsszavakkal és leírásokkal.
========================================================= */

window.SZEFO_SEARCH_INDEX = [
  {
    id: "kezdolap",
    title: "Kezdőlap",
    url: "../../index.html",
    category: "Főoldal",
    keywords: [
      "SZEFO",
      "SZEFO Közhasznú Nonprofit Zrt.",
      "főoldal",
      "rehabilitációs foglalkoztatás",
      "tevékenységek",
      "üzletágak",
      "üzemegységek",
      "Mérész Attila",
      "vezérigazgató",
      "vezérigazgatói köszöntő",
      "1953",
      "74% MMK",
      "Legrand",
      "Paul Shark",
      "DAMA S.p.A.",
      "Chance márka",
      "e-hulladék",
      "MOHU",
      "sík- és körkötő üzem",
      "vasaló üzem",
      "mosó-kikészítő üzem",
      "szabászat",
      "logisztika",
      "hímző- és szitanyomó üzem",
      "varróüzem",
      "Minőségellenőrzési Osztály",
      "MEO"
    ],
    text: "A SZEFO.hu kezdőoldala: 1953 óta Magyarország egyik legrégebbi rehabilitációs foglalkoztatója, jelenleg mintegy 500 munkatárssal, akiknek 74%-a megváltozott munkaképességű. Vezérigazgatói köszöntő Mérész Attilától. Fő tevékenységek: divat- és kötöttáru gyártás (Chance saját márka, Paul&Shark / DAMA S.p.A. partnerség), villamosipari bérmunka (Legrand áramelosztó-szabályozó készülékek), valamint e-hulladék (MOHU) hulladékgazdálkodás. Üzemegységeink: sík- és körkötő üzem, félkész- és készáruvasaló üzem, mosó-kikészítő és fércelő üzem, szabászat, logisztika, hímző- és szitanyomó üzem, varróüzem, Minőségellenőrzési Osztály (MEO). Kapcsolódó oldalak: Alapítvány, Partnerek, Referenciák."
  },
  {
    id: "tortenetunk",
    title: "Történetünk",
    url: "../tortenetunk/index.html",
    category: "Rólunk",
    keywords: [
      "történet",
      "timeline",
      "időszalag",
      "mérföldkövek",
      "SZEFO története",
      "alapítás",
      "fejlődés",
      "Jáksó László",
      "Szegedi Fonalmentő Vállalat",
      "Kontavil",
      "1990 Legrand",
      "2001 Paul Shark DAMA",
      "2008 Szegedi Tudományegyetem",
      "2010 Chance márka",
      "2021 Szeged-Csanádi Egyházmegye",
      "tulajdonosváltás"
    ],
    text: "A SZEFO idővonalas története 1953-tól napjainkig. 1953: Dr. Jáksó László és 26 vak, gyengénlátó sorstársa megalapítja a Szegedi Fonalmentő Vállalatot. 1960: textilipari tevékenység bővülése, kötőrészleg. 1970: technológiai beruházások. 1990: Legrand-együttműködés kezdete (Kontavil). 1993: a Magyar Állam tulajdonába kerül. 1998: a SZEFO Közhasznú Nonprofit Zrt. megújulása. 2001: Paul & Shark / DAMA S.p.A. nemzetközi divatipari partnerség. 2008: K+F együttműködés a Szegedi Tudományegyetemmel. 2010: a Chance márka megalapítása. 2013–2019: új hazai divatmárka-együttműködések (ABRON, AERON, Kata Szegő, Nanushka, Pápai Lilla, Tomcsányi). 2021: tulajdonosváltás, a társaság a Szeged-Csanádi Egyházmegye tulajdonába kerül."
  },
  {
    id: "kuldetesunk",
    title: "Küldetésünk",
    url: "../kuldetesunk/index.html",
    category: "Rólunk",
    keywords: [
      "küldetés",
      "filozófia",
      "megváltozott munkaképesség",
      "MMK",
      "társadalmi felelősségvállalás",
      "foglalkoztatás",
      "74% MMK",
      "CAD",
      "digitális gyártás-előkészítés",
      "diszkriminációmentesség",
      "esélyegyenlőség",
      "energiatakarékosság",
      "textilhulladék csökkentése"
    ],
    text: "A SZEFO küldetése 1953 óta: méltó munkalehetőség, szakmai támogatás és biztonságos munkakörülmények biztosítása megváltozott munkaképességű, fogyatékossággal élő és egészségkárosodott emberek számára. Munkavállalóink 74%-a megváltozott munkaképességű (MMK) munkatárs. Filozófiánk a megbízható minőségre, a korszerű CAD gyártás-előkészítő szoftverre és a felelős, energia- és anyagtakarékos, textilhulladék-csökkentő gyártásra épül. Alapelveink: pontos gyártói határidők, felelősségvállalás munkatársainkért és a természetért, energiahatékony megoldások, folyamatos innováció."
  },
  {
    id: "kapcsolat",
    title: "Kapcsolat",
    url: "../kapcsolat/index.html",
    category: "Információ",
    keywords: [
      "kapcsolat",
      "elérhetőség",
      "cím",
      "telefon",
      "email",
      "ügyfélszolgálat",
      "titkarsag@szefo.hu",
      "Facebook",
      "LinkedIn",
      "TikTok",
      "Instagram",
      "közösségi média"
    ],
    text: "Elérhetőségeink: székhely 6724 Szeged, Tavasz utca 2., telefon +36-62-554-054, e-mail titkarsag@szefo.hu. Kövesse híreinket Facebook, LinkedIn, TikTok és Instagram oldalainkon is."
  },
  {
    id: "altalanos-ceginformaciok",
    title: "Általános céginformáció",
    url: "../altalanos_ceginformaciok/index.html",
    category: "Céginformációk",
    keywords: [
      "céginformáció",
      "általános",
      "adatok",
      "vállalati információ",
      "cégadatok",
      "tulajdonos",
      "részvényes",
      "egyházmegye",
      "vezérigazgató",
      "Mérész Attila",
      "Kiss Andrea",
      "Vas László",
      "Musa Imre",
      "Szilléry Annamária",
      "Vígh Norbert",
      "vezetőség",
      "székhely",
      "telephely",
      "fióktelep",
      "Chance Bolt",
      "elérhetőség",
      "teáor",
      "TEÁOR 1439",
      "tevékenységi kör",
      "saját tőke",
      "jegyzett tőke",
      "CHANCE védjegy",
      "alapszabály",
      "szervezeti és működési szabályzat",
      "SZMSZ",
      "adatvédelmi szabályzat",
      "javadalmazási szabályzat",
      "etikai kódex",
      "szabályzatok",
      "jogszabályok",
      "szervezeti felépítés",
      "PDF"
    ],
    text: "A társaság alapítója és 100%-os tulajdonosa 2021. december 29. óta a Szeged-Csanádi Egyházmegye (korábban a Magyar Állam nevében az MNV Zrt., majd az Emberi Erőforrások Minisztériuma gyakorolta a tulajdonosi jogokat). Vezérigazgató: Mérész Attila, vezérigazgató-helyettes: Kiss Andrea. Igazgatóságok vezetői: Vas László (gazdasági igazgató), Musa Imre (HR igazgató), Szilléry Annamária (termelési igazgató), Vígh Norbert (Legrand-, E-projekt igazgató). Székhely és központi telephely: 6724 Szeged, Tavasz u. 2. Telephelyek és fióktelepek: Szeged (Dorozsmai út), Apátfalva, Hódmezővásárhely, Makó, Orosháza, Szentes. Chance márkabolt: 6720 Szeged, Tisza Lajos krt. 75. Főtevékenység (TEÁOR 1439): egyéb kötött, hurkolt ruházati termék gyártása; további tevékenységek: áramelosztó-szabályozó készülék gyártása, villanyszerelés, textil- és ruházati kis- és nagykereskedelem, oktatás. A CHANCE védjegy lajstromszáma 186057/2005. Letölthető szabályzatok: Alapszabály, SZMSZ, Adatvédelmi-adatbiztonsági szabályzat, Javadalmazási Szabályzat, Etikai Kódex, Közérdekű Adatok Közzétételének Szabályzata, valamint a vonatkozó jogszabályok jegyzéke és a szervezeti felépítést bemutató ábra."
  },
  {
    id: "kozerdeku-adatok",
    title: "Közérdekű adatok",
    url: "../kozerdeku_adatok/index.html",
    category: "Céginformációk",
    keywords: [
      "közérdekű",
      "adatok",
      "nyilvános adatok",
      "közzététel",
      "közadat",
      "általános közzétételi lista",
      "Infotv.",
      "2011. évi CXII. törvény",
      "szervezeti adatok",
      "személyzeti adatok",
      "gazdálkodási adatok",
      "Cg.06-10-000122",
      "adószám",
      "NAIH",
      "Falk Miksa utca",
      "adatvédelmi tisztviselő",
      "Budapest Főváros Kormányhivatal",
      "SZEFO Magazin",
      "Gyurácz Annamária",
      "SZEFO Fonalfeldolgozó Chance Alapítvány",
      "Ambrus Norbert",
      "közbeszerzés",
      "EKR szerződéstár",
      "számviteli beszámoló",
      "Állami Számvevőszék"
    ],
    text: "Az Infotv. (2011. évi CXII. törvény) szerinti általános közzétételi lista. Cégadatok: SZEFO Közhasznú Nonprofit Zrt., székhely 6724 Szeged, Tavasz u. 2., cégjegyzékszám Cg.06-10-000122, adószám 11090036-2-06, jegyzett tőke 1.100.000 eFt. Szervezeti és személyzeti adatok: vezetők, szervezeti egységek, telephelyek, a SZEFO Fonalfeldolgozó Chance Alapítvány (kuratóriumi tagok: dr. Ambrus Norbert, Kiss Andrea), a SZEFO Magazin kiadvány (főszerkesztő: Gyurácz Annamária). Felügyeleti szervek: Budapest Főváros Kormányhivatal (rehabilitációs hatóság) és a Nemzeti Adatvédelmi és Információszabadság Hatóság (NAIH, 1055 Budapest, Falk Miksa u. 9-11.). Tevékenységre és működésre vonatkozó adatok: szabályzatok, jogszabályok, közérdekű adatigénylés rendje. Gazdálkodási adatok: Állami Számvevőszéki ellenőrzés, számviteli beszámolók, foglalkoztatottak létszáma és béradatai, közbeszerzés (EKR szerződéstár), a megváltozott munkaképességű munkavállalók rehabilitációs foglalkoztatásához nyújtott támogatási szerződés."
  },
  {
    id: "kepzo-intezmenyek",
    title: "Képző intézmények",
    url: "../kepzo_intezmenyek/index.html",
    category: "Céginformációk",
    keywords: [
      "képző intézmények",
      "képzés",
      "oktatás",
      "tanulás",
      "felnőttképzés",
      "okj",
      "efop",
      "Péli Katalin",
      "E-001255/2015",
      "textiltermék összeállító",
      "férfi szabó",
      "női szabó",
      "kötőgép kezelő",
      "kötöttáru mosodai gépkezelő",
      "kötöttáru varró szalagmunkás",
      "ruhaipari sablonkivágó",
      "kompetenciafejlesztés",
      "konfliktuskezelés",
      "önismeret",
      "stresszkezelés",
      "digitális kompetencia"
    ],
    text: "A SZEFO Közhasznú Nonprofit Zrt. felnőttképző intézményének nyilvántartásba vételi száma E-001255/2015, képzési vezető Péli Katalin. „A” képzési körben OKJ szerinti szakmai képzések: Textiltermék összeállító (21 542 02), Férfi szabó (34 542 04), Női szabó (34 542 06). „B” képzési körben egyéb szakmai képzések: Betanított kötőgép kezelő, Betanított kötöttáru mosodai gépkezelő, Betanított kötöttáru varró szalagmunkás, Kötöttáru alapanyag és kellék nyilvántartó, Ruhaipari sablonkivágó. „D” képzési körben kompetenciafejlesztő tréningek: társadalmi és munkaerő-piaci beilleszkedés, hatékony kommunikáció és konfliktuskezelés, munkaerő-piaci ismeretek, önismeret, stressz- és krízishelyzetek kezelése, tanulási technikák, digitális kompetenciafejlesztés. Az EFOP-1.1.6-17-2017-00006 projekt keretében 240 fő vett részt a képzéseken, 228 fő szerzett tanúsítványt."
  },
  {
    id: "projektek",
    title: "Projektek",
    url: "../projektek/index.html",
    category: "Céginformációk",
    keywords: [
      "projektek",
      "fejlesztések",
      "programok",
      "pályázatok",
      "támogatás",
      "efop",
      "gop",
      "széchenyi 2020",
      "tranzitfoglalkoztatás",
      "megváltozott munkaképesség",
      "eszközbeszerzés",
      "európai regionális fejlesztési alap",
      "63 917 482 Ft",
      "144 591 952 Ft"
    ],
    text: "Megvalósult hazai és uniós társfinanszírozású pályázati programjaink. EFOP-1.1.6-17-2017-00006 „Szegedi SZEFO zrt. a megváltozott munkaképességű személyek tranzitálásának elősegítéséért”: 63 917 482 Ft vissza nem térítendő támogatás a Széchenyi 2020 program keretében, 2017.09.01–2019.04.30, 240 fő bevonásával, 228 fő tanúsítvánnyal zárva, 9 fő nyílt munkaerőpiaci elhelyezkedéssel. GOP-3.5.1-15/A-2015-0003 „Eszközbeszerzés és információs technológia fejlesztése a SZEFO Zrt-nél”: 144 591 952 Ft támogatás (50%-os intenzitás) az Európai Regionális Fejlesztési Alapból. Letölthető dokumentumok: támogatási szerződések, projekt tájékoztató táblák, adatvédelmi tájékoztató és támogatói okiratok PDF formátumban."
  },
  {
    id: "minosegpolitika",
    title: "Minőségpolitika",
    url: "../minosegpolitika/index.html",
    category: "Céginformációk",
    keywords: [
      "minőségpolitika",
      "minőség",
      "ISO",
      "tanúsítvány",
      "minőségirányítás",
      "ISO 9001",
      "ISO 14001",
      "ISO 45001",
      "KIR",
      "MEBIR",
      "integrált irányítási rendszer",
      "környezetközpontú irányítás",
      "munkahelyi egészségvédelem",
      "munkabiztonság",
      "CERTOP",
      "King Cert",
      "I1768985033Q",
      "audit",
      "PDF"
    ],
    text: "A SZEFO Közhasznú Nonprofit Zrt. integrált irányítási rendszert működtet. ISO 9001:2015 minőségirányítási rendszer (King Cert International Certification Ltd., tanúsítvány száma I1768985033Q, érvényes 2027.01.25-ig). ISO 14001:2015 környezetközpontú irányítási rendszer (KIR, tanúsítvány 01-20772/23-15490) és ISO 45001:2018 munkahelyi egészségvédelem és biztonság irányítási rendszere (MEBIR, tanúsítvány 01-20772/23-15491) – mindkettő CERTOP Termék- és Rendszertanúsító Kft., érvényes 2026.09.14-ig, magyar, angol és olasz nyelven is elérhető. Tanúsított tevékenységi terület: kötött ruhaipari termékek fejlesztése, gyártása és értékesítése. Letölthető a minőségpolitikai nyilatkozat és valamennyi tanúsítvány PDF formátumban."
  },
  {
    id: "partnerek",
    title: "Partnerek",
    url: "../partnerek/index.html",
    category: "Céginformációk",
    keywords: [
      "partnerek",
      "együttműködés",
      "érdekvédelem",
      "SINOSZ",
      "MEOSZ",
      "ÉFOÉSZ",
      "Vakok és Gyengénlátók Egyesülete",
      "fogyatékosügy",
      "esélyegyenlőség"
    ],
    text: "A SZEFO Közhasznú Nonprofit Zrt. érdekvédelmi partnerei: Vakok és Gyengénlátók Csongrád-Csanád Megyei Egyesülete, SINOSZ – Siketek és Nagyothallók Országos Szövetsége, MEOSZ – Mozgáskorlátozottak Egyesületeinek Országos Szövetsége, ÉFOÉSZ – Értelmi Fogyatékossággal Élők és Segítőik Országos Érdekvédelmi Szövetsége. E partnerségek szakmai háttértudást, tapasztalati szakértelmet és érzékenyítést nyújtanak a befogadó, esélyegyenlőségen alapuló foglalkoztatáshoz."
  },
  {
    id: "alapitvany",
    title: "Alapítvány",
    url: "../alapitvany/index.html",
    category: "Céginformációk",
    keywords: [
      "alapítvány",
      "SZEFO Chance",
      "Chance Alapítvány",
      "közhasznú alapítvány",
      "dokumentumok",
      "PDF",
      "adószám",
      "18285491-1-06",
      "számlaszám",
      "kuratórium"
    ],
    text: "A SZEFO Fonalfeldolgozó Chance Közhasznú Alapítvány (cím: 6724 Szeged, Tavasz utca 2., adószám 18285491-1-06, számlaszám 11600006-00000000-95879064) célja a hátrányos helyzetű, fogyatékos, illetve megváltozott munkaképességű emberek társadalmi integrációja: foglalkozási rehabilitáció és tranzitfoglalkoztatás segítése, képzési projektek, szabadidős és családi programok szervezése, nyílt munkaerőpiaci elhelyezkedés támogatása. Letölthető dokumentumok: alapító okirat, kuratóriumi jegyzőkönyvek és meghívók, egyszerűsített éves beszámolók és közhasznúsági mellékletek, közhasznú jogosultságról szóló végzések."
  },
  {
    id: "adatszolgaltatas",
    title: "Adatszolgáltatás",
    url: "../adatszolgaltatas/index.html",
    category: "Céginformációk",
    keywords: [
      "adatszolgáltatás",
      "adatok",
      "közzététel",
      "nyilvános információ",
      "takarékos törvény",
      "2009. évi CXXII. törvény",
      "javadalmazás",
      "vezető tisztségviselő",
      "felügyelő bizottság",
      "alapbér",
      "végkielégítés",
      "felmondási idő",
      "megbízási díj",
      "cégjegyzés",
      "közüzemi szerződés",
      "foglalkoztatottak létszáma",
      "versenytilalmi megállapodás"
    ],
    text: "A köztulajdonban álló gazdasági társaságok takarékosabb működéséről szóló 2009. évi CXXII. törvény (Takarékos törvény) alapján közzétett adatok évenkénti bontásban, 2009-től 2021-ig. Minden évre vonatkozóan: a vezető tisztségviselő és a vezető állású munkavállalók jogviszonya és javadalmazása (alapbér, prémium, felmondási idő, végkielégítés, versenytilalmi megállapodás), a Felügyelő Bizottság tagjainak megbízási díja, az együttes cégjegyzésre és bankszámla feletti rendelkezésre jogosult, valamint a munkáltató szempontjából meghatározó jelentőségű munkavállalók (igazgatók, fióktelep-vezetők) adatai, továbbá a foglalkoztatottak statisztikai állományi létszáma és személyi juttatásainak összesített adatai."
  },
  {
    id: "adatigenyles-rendje",
    title: "Adatigénylés rendje",
    url: "../adatigenyles_rendje/index.html",
    category: "Céginformációk",
    keywords: [
      "adatigénylés",
      "adatigénylés rendje",
      "közérdekű adatigénylés",
      "információigénylés",
      "adatkezelési tájékoztató",
      "szabályzat",
      "Infotv.",
      "2011. évi CXII. törvény",
      "információszabadság",
      "Péli Katalin",
      "adatvédelmi tisztviselő",
      "adatvedelmitisztviselo@szefo.hu",
      "PDF"
    ],
    text: "A közérdekű adatok megismerésére irányuló igények az Infotv. (2011. évi CXII. törvény) alapján nyújthatók be. Adatvédelmi tisztviselő: Péli Katalin (adatvedelmitisztviselo@szefo.hu, +36-62-554-054, 6724 Szeged, Tavasz u. 2.). Letölthető a közérdekű adatok megismerése iránti igény teljesítésének szabályzata (6 oldal) és az ehhez kapcsolódó adatkezelési tájékoztató (2 oldal) PDF formátumban."
  },
  {
    id: "eves-beszamolok",
    title: "Éves beszámolók",
    url: "../eves_beszamolok/index.html",
    category: "Céginformációk",
    keywords: [
      "éves beszámoló",
      "beszámolók",
      "pénzügyi beszámoló",
      "e-beszámoló",
      "céginformációs szolgálat",
      "igazságügyi minisztérium",
      "beszámolókereső",
      "e-beszamolo.im.gov.hu"
    ],
    text: "A SZEFO Közhasznú Nonprofit Zrt. hivatalos éves beszámolói az Igazságügyi Minisztérium Céginformációs és az Elektronikus Cégeljárásban Közreműködő Szolgálatának online beszámolókeresőjében (e-beszamolo.im.gov.hu) érhetők el."
  },
  {
    id: "kozzetetelek",
    title: "Közzétételek",
    url: "../kozzetetelek/index.html",
    category: "Céginformációk",
    keywords: [
      "közzétételek",
      "közzététel",
      "nyilvános információ",
      "dokumentum",
      "energetikai szakreferens",
      "energetikai jelentés",
      "energiahatékonyság",
      "energiafelhasználás",
      "CO2 kibocsátás",
      "szén-dioxid",
      "2015. évi LVII. törvény",
      "122/2015. Korm. rendelet",
      "PDF"
    ],
    text: "Az energiahatékonyságról szóló 2015. évi LVII. törvény és a 122/2015. (V. 26.) Korm. rendelet alapján közzétett éves energetikai szakreferens jelentések 2017-től 2025-ig, évenkénti PDF formátumban. A jelentések bemutatják az energiafelhasználást, a szén-dioxid-kibocsátást, az energiahatékonyságot javító intézkedéseket és a szemléletformálás lépéseit."
  },
  {
    id: "ellenorzesek",
    title: "Ellenőrzések",
    url: "../ellenorzesek/index.html",
    category: "Céginformációk",
    keywords: [
      "ellenőrzések",
      "vizsgálatok",
      "dokumentumok",
      "kontroll",
      "Állami Számvevőszék",
      "ÁSZ",
      "ÁSZ jelentés",
      "19127",
      "állami tulajdonú gazdasági társaságok",
      "audit",
      "asz.hu",
      "PDF"
    ],
    text: "Az Állami Számvevőszék 2019-ben, az állami tulajdonú gazdasági társaságok ellenőrzése keretében vizsgálta a SZEFO Közhasznú Nonprofit Zrt. (akkori nevén Szegedi SZEFO Fonalfeldolgozó zrt.) működését. A 19127 számú ÁSZ-jelentés nyilvános megállapításai PDF formátumban letölthetők, és a www.asz.hu oldalon is elérhetők."
  },
  {
    id: "szerzodesek",
    title: "Szerződések",
    url: "../szerzodesek/index.html",
    category: "Céginformációk",
    keywords: [
      "szerződések",
      "megállapodások",
      "dokumentumok",
      "PDF",
      "keret- és támogatási szerződés",
      "támogatási szerződés",
      "rehabilitációs foglalkoztatás",
      "egyéni támogatás",
      "2009. évi CXXII. törvény",
      "KBA",
      "közbeszerzés",
      "kozbeszerzes.hu"
    ],
    text: "A köztulajdonban álló gazdasági társaságok takarékosabb működéséről szóló 2009. évi CXXII. törvény 2. § (3)-(4) bekezdése szerinti szerződések a KBA rendszerben (kereso-core.kozbeszerzes.hu) érhetők el. Letölthető mellékletek: a megváltozott munkaképességű munkavállalók rehabilitációs foglalkoztatásához nyújtható egyéni támogatásra kötött Keret- és Támogatási szerződések (2018, 2019, 2021 és annak módosítása)."
  },
  {
    id: "palyazat-neao",
    title: "Pályázat NEAO-KP-1-2022/8-000016",
    url: "../palyazat/index.html",
    category: "Céginformációk",
    keywords: [
      "pályázat",
      "NEAO-KP-1-2022/8-000016",
      "CHANCE az esélyegyenlőségért és családokért",
      "Nemzeti Együttműködési Alap",
      "esélyegyenlőség",
      "érzékenyítő tréning",
      "szemléletformálás",
      "színházlátogatás",
      "Mórahalom",
      "Rómeó és Júlia",
      "Mikulás",
      "családi nap",
      "Bethlen Gábor Alapkezelő",
      "Vakok és Gyengénlátók Csongrád-Csanád Megyei Egyesülete"
    ],
    text: "A NEAO-KP-1-2022/8-000016 azonosítójú „CHANCE az esélyegyenlőségért és családokért” pályázati program a SZEFO Fonalfeldolgozó Chance Alapítvány megvalósításában, a Nemzeti Együttműködési Alap 1 620 000 Ft támogatásával, 2022.04.01–2023.03.31 között. Programok: színházlátogatás a Mórahalmi Patkó Lovas és Szabadtéri Színházban (Rómeó és Júlia, 100 fő), érzékenyítő és szemléletformáló foglalkozások a székhelyen és 4 fióktelepen a Vakok és Gyengénlátók Csongrád-Csanád Megyei Egyesülete közreműködésével (159 fő), valamint Mikulás-napi családi nap (159 gyermek). Támogatók: Nemzeti Együttműködési Alap, Miniszterelnökség, Bethlen Gábor Alapkezelő."
  },
  {
    id: "hireink",
    title: "Hírek és blog",
    url: "../hireink/index.html",
    category: "Hírek és blog",
    keywords: [
      "hírek",
      "hír",
      "blog",
      "aktualitások",
      "újdonságok",
      "események",
      "céges hírek",
      "szakmai blog",
      "közösség",
      "fenntarthatóság",
      "rehabilitációs foglalkoztatás",
      "Gál Ferenc Egyetem",
      "stratégiai együttműködés",
      "duális képzés",
      "Dux László",
      "Tóth József"
    ],
    text: "A SZEFO hírei és blogbejegyzései egy helyen, kategóriák szerint szűrhető és kereshető felületen (Céges hírek, Közösség, Események / Szakmai blog, Fenntarthatóság, Történetek). Kiemelt hír: 2026. január 9-én a Gál Ferenc Egyetem (Prof. Dr. Dux László rektor, Tóth József kancellár) és a SZEFO Közhasznú Nonprofit Zrt. (Mérész Attila vezérigazgató) stratégiai együttműködési megállapodást írt alá a textil- és könnyűipari duális szakképzés erősítéséért; a 2026/2027-es tanévtől a diákok a SZEFO gyártóegységeiben tölthetik szakmai gyakorlatukat."
  },
  {
    id: "szefo-magazin",
    title: "Korábbi SZEFO Magazinok",
    url: "../szefo_magazin/index.html",
    category: "Hírek és blog",
    keywords: [
      "SZEFO Magazin",
      "magazin",
      "lapszám",
      "újság",
      "vállalati újság",
      "archívum",
      "korábbi lapszámok",
      "PDF",
      "letöltés",
      "Szentesi Fióktelep",
      "COVID",
      "Németné Janó Beáta",
      "SZEFO Manók"
    ],
    text: "A SZEFO Magazin vállalati újság archívuma, 8 lapszám 2019 és 2026 között, online olvasható és letölthető PDF formátumban. Témák évek szerint: 2026 – interjú az új vezérigazgatóval és egy 40 éve dolgozó munkatárssal; 2023 – a Szentesi Fióktelep bemutatása; 2022 – a COVID-járvány kezelése, foglalkozás-egészségügyi csapat; 2021 – megemlékezés Németné Janó Beátáról; 2020 – SZEFO Manók nyári tábor és a koronavírus-járvány kezdete; 2019 – nyugdíjas találkozó és az első lapszám bemutatkozása."
  },
  {
    id: "e-hulladek",
    title: "E-hulladék",
    url: "../e-hulladek/index.html",
    category: "Rólunk",
    keywords: [
      "e-hulladék",
      "elektronikai hulladék",
      "újrahasznosítás",
      "hulladékgazdálkodás",
      "MOHU",
      "Hódmezővásárhely",
      "Erzsébeti út",
      "KÜJ",
      "KTJ",
      "fémkereskedelmi engedély",
      "hulladékgazdálkodási engedély"
    ],
    text: "A SZEFO hulladékgazdálkodási tevékenysége a hódmezővásárhelyi telephelyen (6800 Hódmezővásárhely, Erzsébeti út 8., KÜJ 100214695, KTJ 103002793) veszélyes és nem veszélyes hulladékok gyűjtésére és előkezelésére terjed ki: elektronikai hulladékok (16-os főcsoport) kézi bontása és válogatása, hűtő- és klímaberendezések gyűjtése, fém- és csomagolási hulladékok gyűjtése. Kezelési kódok: R12, E02-05, E02-06, E02-08. Letölthető dokumentumok: fémkereskedelmi engedély, hulladékgazdálkodási engedély, telepengedély és engedélymódosítás, MOHU sajtóközlemény."
  },
  {
    id: "karrier",
    title: "Karrier",
    url: "../karrier/index.html",
    category: "Karrier",
    keywords: [
      "karrier",
      "állás",
      "munka",
      "jelentkezés",
      "foglalkoztatás",
      "munkalehetőség",
      "állásajánlat",
      "megváltozott munkaképesség",
      "részmunkaidő",
      "Fogyatékosság-barát munkahely",
      "alkatrészszerelő",
      "udvaros",
      "anyagmozgató",
      "rakodómunkás",
      "adminisztrátor",
      "adminisztrációs ügyintéző",
      "takarító",
      "portás",
      "raktáros",
      "karbantartó",
      "villanyszerelő",
      "targoncás",
      "gépbeállító",
      "kazángépkezelő",
      "EKÁER",
      "fióktelepvezető"
    ],
    text: "Aktuális állásajánlataink megváltozott munkaképességű munkavállalók számára, jellemzően részmunkaidőben, napi 4 órában, két műszakban. 2010-ben elnyertük a Fogyatékosság-barát munkahely elismerést; munkatársaink 74%-a megváltozott munkaképességű. Nyitott pozíciók: fióktelepvezető, alkatrészszerelő, udvaros, anyagmozgató és rakodómunkás, adminisztrátor, adminisztrációs ügyintéző, takarító, portás, raktáros, karbantartó, villanyszerelő, targoncás rakodómunkás, gépbeállító, kazángépkezelő, EKÁER-ügyintéző. Munkavégzés helyszínei: Szeged (Tavasz utca, Dorozsmai út), Makó, Szentes, Hódmezővásárhely, Apátfalva és Orosháza. Jelentkezés: karrier@szefo.hu, +36 (30) 243-0585, illetve +36 (62) 554-054/108."
  },
  {
    id: "klaszter",
    title: "Klaszter",
    url: "../klaszter/index.html",
    category: "Információ",
    keywords: [
      "klaszter",
      "együttműködés",
      "hálózat",
      "partnerség"
    ],
    text: "Klaszterrel kapcsolatos oldal, jelenleg fejlesztés alatt."
  }
];
